title : RafaDev
timezone: America/Sao_Paulo

url: rafadev.com
baseurl: /
permalink: /:categories/:title/
tags_path: /tags/
archive_path: /arquivo/
map_path: /mapa/

paginate: 2
paginate_path: 'pagina:num'
# For better related posts
lsi: true

author :
  name : Rafael Henrique Moreira
  email : rafadev7@gmail.com
  url : http://rafadev.com/

github_url: http://github.com/rafadev7/RafaDev.com/
feedburner_url: http://feeds.feedburner.com/RafaDev
disqus_id: rafadev
google_analytics_id: UA-40858650-1